# For more information, see: https://github.com/commercialhaskell/stack/blob/release/doc/yaml_configuration.md

resolver: lts-13.9
packages:
  - '.'
extra-deps: []
flags:
  queryforest:
    test: false
extra-package-dbs: []